
site_name: Trackerboy
site_description: Gameboy / Gameboy Color music tracker
site_url: https://www.trackerboy.org/manual
repo_url: https://github.com/stoneface86/trackerboy
repo_name: stoneface86/trackerboy
edit_uri: edit/develop/docs/

extra_javascript: 
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

extra_css:
  - css/extra.css

markdown_extensions:
    - mdx_math
    - meta

theme:
  name: material
#  custom_dir: docs-theme/
  favicon: img/favicon.ico
  logo: img/appicon-48.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tracking
    - navigation.top
    - toc.integrate

nav:
  - 'Home': 'index.md'
  - 'FAQ': 'faq.md'
  - 'Interface':
    - 'Overview': 'interface/index.md'
    - 'Configuration':
      - 'Overview': 'interface/configuration/index.md'
      - 'General': 'interface/configuration/general.md'
      - 'Appearance': 'interface/configuration/appearance.md'
      - 'Keyboard': 'interface/configuration/keyboard.md'
      - 'Sound / Midi': 'interface/configuration/sound.md'
    - 'Menus':
      - 'File': 'interface/menus/file.md'
      - 'Edit': 'interface/menus/edit.md'
      - 'Module': 'interface/menus/module.md'
      - 'Song': 'interface/menus/song.md'
      - 'Instruments': 'interface/menus/instruments.md'
      - 'Waveforms': 'interface/menus/waveforms.md'
      - 'Tracker': 'interface/menus/tracker.md'
      - 'View': 'interface/menus/view.md'
      - 'Help': 'interface/menus/help.md'
    - 'Toolbars': 'interface/toolbars.md'
    - 'Sidebar': 'interface/sidebar.md'
    - 'Pattern editor': 'interface/pattern-editor.md'
    - 'Instruments/Waveforms panel': 'interface/instruments-waveforms.md'
    - 'Instrument editor': 'interface/instrument-editor.md'
    - 'Waveform editor': 'interface/waveform-editor.md'
    - 'Module properties': 'interface/module-properties.md'
    - 'Comments': 'interface/comments.md'
    - 'History': 'interface/history.md'
    - 'Tempo Calculator': 'interface/tempo-calculator.md'
    - 'Shortcuts': 'interface/shortcuts.md'
    - 'Status bar': 'interface/statusbar.md'
    - 'WAV export': 'interface/wav-exporter.md'
    - 'Audio diagnostics': 'interface/audio-diagnostics.md'
  - 'Tracker':
    - 'Overview': 'tracker/index.md'
    - 'Glossary': 'tracker/glossary.md'
    - 'Octave range and notes': 'tracker/octave-range.md'
    - 'Channel locking': 'tracker/channel-lock.md'
    - 'Speed/Tempo': 'tracker/speed.md'
    - 'Instruments': 'tracker/instruments.md'
    - 'Effect list': 'tracker/effect-list.md'
    - 'Sound effects (TBD)': 'tracker/sfx.md'
  - 'Hardware Primer':
    - 'Overview': 'hardware/index.md'
    - 'Pulse channel': 'hardware/pulse-channel.md'
    - 'Wave channel': 'hardware/wave-channel.md'
    - 'Noise channel': 'hardware/noise-channel.md'
    - 'Channel envelope': 'hardware/envelope.md'
    - 'Frequency sweep': 'hardware/sweep.md'
    - 'Volume control and panning': 'hardware/volume-control.md'
  - 'Change log': 'changelog.md'
  - 'License': 'license.md'
